    LIST P=16F84

STATUS  EQU 03H
PORTA   EQU 05H
TRISA   EQU 05H

COUNT   EQU 10H

#DEFINE RA0     PORTA, 0

#DEFINE BANK0   BCF STATUS, 5
#DEFINE BANK1   BSF STATUS, 5

    ORG 0
    BANK1
    CLRF    TRISA       ; Declarado PORTA como salida
    BANK0
    GOTO INICIO

INICIO
    MOVLW   B'00011111'
    MOVWF   PORTA
    GOTO INICIO
END